### ISSUE TITLE
A solve if anyone get "Failed to send request: Operation not permitted"

### ISSUE THREAD

**Issue by gregpalaci** [Admonstrator/glinet-adguard-updater#2]
Basically I upgraded my GL router but it removed adguard plugins so I assume the localhost dns it created wasn't working and I was unable to change "DNS" under the GUI the solve was to manually set a DNS in Luci

Then this package downloaded and worked great

https://techoverflow.net/2020/12/24/how-to-fix-openwrt-opkg-failed-to-send-request-operation-not-permitted/

**Comment by Admonstrator** [comment]
I don't know what this is about my repo, but thanks for sharing.

**Comment by gregpalaci** [comment]
Nothing sorry for the noise, figured it might help someone with the same issue. Upgrading GLirouter, missing and misconfigured adguard, can't use your package faulty DNS. Thanks for your package though. Cheers
